# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

gain:
  _target_: emg2qwerty.transforms.ForEach
  transform:
    _target_: emg2qwerty.transforms.RandomGain
    min_gain: 0.8
    max_gain: 1.2

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 2
  time_mask_param: 12
  n_freq_masks: 1
  freq_mask_param: 4

transforms:
  train: 
    - ${to_tensor}
    - ${gain}
    - ${logspec}
    - ${specaug}

  val:
    - ${to_tensor}
    - ${logspec}

  test: ${transforms.val}